//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTFServer.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountController_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountController_zh_CN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTFServer.Resources.Controllers.AccountController.zh-CN", typeof(AccountController_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户已存在.
        /// </summary>
        internal static string Account_already_exists {
            get {
                return ResourceManager.GetString("Account already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户未激活，请重新注册.
        /// </summary>
        internal static string Account_not_active__please_re_register {
            get {
                return ResourceManager.GetString("Account not active, please re-register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件发送成功.
        /// </summary>
        internal static string Email_sent_successfully {
            get {
                return ResourceManager.GetString("Email sent successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google reCAPTCHA 校验失败.
        /// </summary>
        internal static string Google_reCAPTCHA_verification_failed {
            get {
                return ResourceManager.GetString("Google reCAPTCHA verification failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件无法发送，请联系管理员.
        /// </summary>
        internal static string Mail_cannot_be_sent__please_contact_the_administrator {
            get {
                return ResourceManager.GetString("Mail cannot be sent, please contact the administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请联系管理员重置密码.
        /// </summary>
        internal static string Please_contact_the_administrator_to_reset_your_password {
            get {
                return ResourceManager.GetString("Please contact the administrator to reset your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册功能已禁用.
        /// </summary>
        internal static string Registration_is_disabled {
            get {
                return ResourceManager.GetString("Registration is disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送用户密码重置邮件.
        /// </summary>
        internal static string Sending_user_password_reset_email {
            get {
                return ResourceManager.GetString("Sending user password reset email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送用户验证邮件.
        /// </summary>
        internal static string Sending_user_verification_email {
            get {
                return ResourceManager.GetString("Sending user verification email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册成功，等待邮箱验证.
        /// </summary>
        internal static string Successful_registration__pending_email_verification {
            get {
                return ResourceManager.GetString("Successful registration, pending email verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册成功.
        /// </summary>
        internal static string Successfully_registered {
            get {
                return ResourceManager.GetString("Successfully registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册成功，待审核.
        /// </summary>
        internal static string Successfully_registered__pending_administrator_confirmation {
            get {
                return ResourceManager.GetString("Successfully registered, pending administrator confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知错误.
        /// </summary>
        internal static string Unknown_error {
            get {
                return ResourceManager.GetString("Unknown error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户不存在.
        /// </summary>
        internal static string User_does_not_exist {
            get {
                return ResourceManager.GetString("User does not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可用邮箱后缀.
        /// </summary>
        internal static string Valid_Email_TLDs {
            get {
                return ResourceManager.GetString("Valid Email TLDs", resourceCulture);
            }
        }
    }
}
