//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTFServer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceResource_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResource_zh_CN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTFServer.Resources.ServiceResource.zh-CN", typeof(ServiceResource_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [作弊检查] 队伍 [{0}] 疑似违规 [{1}]，相关队伍 [{2}].
        /// </summary>
        internal static string _Cheat_check__Team___0___suspected_of_cheating_in___1____related_teams___2__ {
            get {
                return ResourceManager.GetString("[Cheat check] Team [{0}] suspected of cheating in [{1}], related teams [{2}]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [实例未知] 未找到队伍 [{0}] 提交 [{1}] 对应题目 [{2}] 的实例.
        /// </summary>
        internal static string _Instance_not_found__Team___0___submitted_answer___1___for_challenge___2__ {
            get {
                return ResourceManager.GetString("[Instance not found] Team [{0}] submitted answer [{1}] for challenge [{2}]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [提交正确] 队伍 [{0}] 提交题目 [{2}] 的答案 [{1}].
        /// </summary>
        internal static string _Submission_accepted__Team___0___submitted_answer___1___for_challenge___2__ {
            get {
                return ResourceManager.GetString("[Submission accepted] Team [{0}] submitted answer [{1}] for challenge [{2}]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [提交错误] 队伍 [{0}] 提交题目 [{2}] 的答案 [{1}].
        /// </summary>
        internal static string _Submission_wrong__Team___0___submitted_answer___1___for_challenge___2__ {
            get {
                return ResourceManager.GetString("[Submission wrong] Team [{0}] submitted answer [{1}] for challenge [{2}]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加全局设置.
        /// </summary>
        internal static string Added_global_config {
            get {
                return ResourceManager.GetString("Added global config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已存在，尝试移除后重新创建.
        /// </summary>
        internal static string already_exists__trying_to_remove_and_recreate {
            get {
                return ResourceManager.GetString("already exists, trying to remove and recreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效的邮件发送调用！.
        /// </summary>
        internal static string Bad_email_sending_call_ {
            get {
                return ResourceManager.GetString("Bad email sending call!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更改邮箱.
        /// </summary>
        internal static string Change_your_email {
            get {
                return ResourceManager.GetString("Change your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查线程 #{0} 发生异常.
        /// </summary>
        internal static string Checker_thread___0__encountered_an_exception {
            get {
                return ResourceManager.GetString("Checker thread #{0} encountered an exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查线程 #{0} 已退出.
        /// </summary>
        internal static string Checker_thread___0__exited {
            get {
                return ResourceManager.GetString("Checker thread #{0} exited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查线程 #{0} 已启动.
        /// </summary>
        internal static string Checker_thread___0__started {
            get {
                return ResourceManager.GetString("Checker thread #{0} started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证邮箱.
        /// </summary>
        internal static string Confirm_your_email {
            get {
                return ResourceManager.GetString("Confirm your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容器.
        /// </summary>
        internal static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容器生命周期检查已启动.
        /// </summary>
        internal static string Container_lifecycle_check_started {
            get {
                return ResourceManager.GetString("Container lifecycle check started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容器生命周期检查已停止.
        /// </summary>
        internal static string Container_lifecycle_check_stopped {
            get {
                return ResourceManager.GetString("Container lifecycle check stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建失败.
        /// </summary>
        internal static string creation_failed {
            get {
                return ResourceManager.GetString("creation failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败.
        /// </summary>
        internal static string deletion_failed {
            get {
                return ResourceManager.GetString("deletion failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker 服务已启动.
        /// </summary>
        internal static string Docker_service_started {
            get {
                return ResourceManager.GetString("Docker service started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件发送遇到问题.
        /// </summary>
        internal static string Error_occurred_while_sending_email {
            get {
                return ResourceManager.GetString("Error occurred while sending email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建容器实例 {0} 失败: {1}.
        /// </summary>
        internal static string Failed_to_create_container_instance__0____1_ {
            get {
                return ResourceManager.GetString("Failed to create container instance {0}: {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建服务失败.
        /// </summary>
        internal static string Failed_to_create_service {
            get {
                return ResourceManager.GetString("Failed to create service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建后未获取到端口暴露信息，创建失败.
        /// </summary>
        internal static string failed_to_get_exposed_port_info_after_creation {
            get {
                return ResourceManager.GetString("failed to get exposed port info after creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法转换端口号：{0}，这是非预期的行为.
        /// </summary>
        internal static string Failed_to_parse_port_number___0___this_is_unexpected_behavior {
            get {
                return ResourceManager.GetString("Failed to parse port number: {0}, this is unexpected behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件发送失败！.
        /// </summary>
        internal static string Failed_to_send_email_ {
            get {
                return ResourceManager.GetString("Failed to send email!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动容器实例 {0} 失败.
        /// </summary>
        internal static string Failed_to_start_container_instance__0_ {
            get {
                return ResourceManager.GetString("Failed to start container instance {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag 检查已启动.
        /// </summary>
        internal static string Flag_checker_started {
            get {
                return ResourceManager.GetString("Flag checker started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag 检查已停止.
        /// </summary>
        internal static string Flag_checker_stopped {
            get {
                return ResourceManager.GetString("Flag checker stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已被销毁.
        /// </summary>
        internal static string has_been_destroyed {
            get {
                return ResourceManager.GetString("has been destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K8s 服务已启动.
        /// </summary>
        internal static string K8s_service_started {
            get {
                return ResourceManager.GetString("K8s service started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拉取容器镜像.
        /// </summary>
        internal static string Pulling_container_image {
            get {
                return ResourceManager.GetString("Pulling container image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除过期容器.
        /// </summary>
        internal static string Removed_expired_container {
            get {
                return ResourceManager.GetString("Removed expired container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置密码.
        /// </summary>
        internal static string Reset_your_password {
            get {
                return ResourceManager.GetString("Reset your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 响应.
        /// </summary>
        internal static string response {
            get {
                return ResourceManager.GetString("response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新开始检查 {0} 个 flag.
        /// </summary>
        internal static string Restarted_checking__0__flags {
            get {
                return ResourceManager.GetString("Restarted checking {0} flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送邮件：.
        /// </summary>
        internal static string Sent_email_to__ {
            get {
                return ResourceManager.GetString("Sent email to: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始处理队伍 {0} 的提交: {1}.
        /// </summary>
        internal static string Started_processing_submission_for_Team__0____1_ {
            get {
                return ResourceManager.GetString("Started processing submission for Team {0}: {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 题目 [{0}] 疑似发生违规，相关队伍 [{1}] 和 [{2}].
        /// </summary>
        internal static string Suspected_cheating_in_challenge___0____related_teams___1___and___2__ {
            get {
                return ResourceManager.GetString("Suspected cheating in challenge [{0}], related teams [{1}] and [{2}]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务取消，检查线程 #{0} 将退出.
        /// </summary>
        internal static string Task_cancelled__checker_thread___0__will_exit {
            get {
                return ResourceManager.GetString("Task cancelled, checker thread #{0} will exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法加载 K8s 配置文件，请确保挂载 /app/k8sconfig.yaml.
        /// </summary>
        internal static string Unable_to_load_K8s_config_file__please_ensure_that__app_k8sconfig_yaml_is_mounted {
            get {
                return ResourceManager.GetString("Unable to load K8s config file, please ensure that /app/k8sconfig.yaml is mounted" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新全局设置.
        /// </summary>
        internal static string Updated_global_config {
            get {
                return ResourceManager.GetString("Updated global config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你正在进行账户注册操作，我们需要验证你的注册邮箱：{0}，请点击下方按钮进行验证。.
        /// </summary>
        internal static string You_are_in_the_process_of_account_registration_operation__we_need_to_verify_your_registered_email___0___please_click_the_button_below_to_verify_ {
            get {
                return ResourceManager.GetString("You are in the process of account registration operation, we need to verify your " +
                        "registered email: {0}, please click the button below to verify.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你正在进行账户邮箱更换操作，请点击下方按钮验证你的新邮箱。.
        /// </summary>
        internal static string You_are_in_the_process_of_changing_your_account_email_address__please_click_the_button_below_to_verify_your_new_email_address_ {
            get {
                return ResourceManager.GetString("You are in the process of changing your account email address, please click the b" +
                        "utton below to verify your new email address.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你正在进行账户密码重置操作，请点击下方按钮重置你的密码。.
        /// </summary>
        internal static string You_are_in_the_process_of_resetting_your_account_password__please_click_the_button_below_to_reset_your_password_ {
            get {
                return ResourceManager.GetString("You are in the process of resetting your account password, please click the butto" +
                        "n below to reset your password.", resourceCulture);
            }
        }
    }
}
